name: Android Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: add BaseURL
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: echo 'BASE_URL=${{ secrets.BASE_URL }}' > ./local.properties
      - name: add ApiKey
        env:
          BASE_URL: ${{ secrets.API_KEY }}
        run: echo 'API_KEY=${{ secrets.API_KEY }}' > ./local.properties
      - name: add keyAlias
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: echo 'keyAlias=${{ secrets.KEY_ALIAS }}' >> ./local.properties

      - name: Decrypt Keystore
        env:
          KEY_BASE64: ${{ secrets.KEY_BASE64 }}
        run: |
          echo "$KEY_BASE64" | base64 --decode > goodhub.jks

      - name: Add path of goodhub.jks to local.properties
        run: |
          echo "storeFile=$(pwd)/goodhub.jks" >> ./local.properties

      - name: add storePassword
        env:
          KEY_STORE_PASS: ${{ secrets.KEYSTORE_PASS }}
        run: echo 'storePassword=${{ secrets.KEYSTORE_PASS }}' >> ./local.properties

      - name: add keyPassword
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASS }}
        run: echo 'keyPassword=${{ secrets.KEY_PASS }}' >> ./local.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Checks
        run: find . -type f -name "*.apk"

      - uses: r0adkll/sign-android-release@v1
        name: Signing APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEY_PASS }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Retrieve Version
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q printVersionName)"
        id: android_version

      - name: Get version
        run: |
          echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV

      - name: Generate file name env var
        run: |
          VERSION_NAME=${{env.version_name}}
          DATE=$(date +'%d.%m.%Y')
          BRANCH_NAME=${GITHUB_REF##*/}
          MESSAGE=$(cat << EOF
          Goodhub-release-${VERSION_NAME}-${BRANCH_NAME}-${DATE}
          EOF)
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV

      - name: Verify APK existence
        run: |
          echo "Checking if the APK file exists..."
          ls -al ./app/build/outputs/apk/release/
      - name: Rename APK
        run:
          mv "./app/build/outputs/apk/release/app-release-signed.apk" "./app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk"
      - name: Verify APK existence
        run: |
          echo "Checking if the APK file exists..."
          ls -al ./app/build/outputs/apk/release/

      - name: Release APK
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ./app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk
          name: ${{env.version_name}}
          tag_name: ${{env.version_name}}
          token: ${{ secrets.TOKEN}}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk